### ISSUE TITLE
stringObjs support

### ISSUE THREAD

**Issue by MultiMote** [leeoniya/uDSV#14]
Hello!
I need to convert CSV to key:value dictionary. Values need to be string-typed.

From the example, I realized that there are two options:
* Parse to string arrays
* Parse to key:value, but values are typed

```js
// native format (fastest)
let stringArrs = parser.stringArrs(csvStr); // [ ['1','2','3'], ['4','5','6'] ]
// typed formats (internally converted from native)
let typedObjs  = parser.typedObjs(csvStr);  // [ {a: 1, b: 2, c: 3}, {a: 4, b: 5, c: 6} ]
```

There is no way to parse csv to objects where values are strings.

**Comment by leeoniya** [comment]
worth adding, i think

**Comment by leeoniya** [comment]
just realized the solution is to add one line to modify the parsed schema to set all columns to string type:

https://jsfiddle.net/zv89euo5/

```js
const { inferSchema, initParser } = uDSV;

const csvStr = `
a,b
1,50000
10,5
`.trim();

const schema = inferSchema(csvStr);

// set all columns as strings
schema.cols.forEach(c => { c.type = 's' });

const parser = initParser(schema);

const data = parser.typedObjs(csvStr);

console.log(data);
```

**Comment by mz8i** [comment]
This is obviously a very simple fix, thanks @leeoniya ! Though it definitely feels like the interface of the library should allow this more explicitly, or that at least it would be worth giving this as an example explicitly in the docs. I was initially confused and wondering if I was missing something in the docs about such a functionality, until I found this issue.

The main use case where this comes in handy is where I don't know the list of columns, but I know that all of the should be read as strings. But also, it's easiest for me to just get an array of objects from the parser. This feels like a very common case?

In terms of an interface, if `parser.stringObjs()` is not desirable for some reason, it would make most sense to have an option for `inferSchema`, something like:
```
inferSchema(csvText, { type: 's' })
```

**Comment by leeoniya** [comment]
added in 55686c5
