### ISSUE TITLE
Replace const enum in .d.ts with string literal union

### ISSUE THREAD

**Issue by mz8i** [leeoniya/uDSV#15]
Thanks for the great library!
I'm having an issue related to https://github.com/leeoniya/uDSV/issues/6 after using the suggested fix to https://github.com/leeoniya/uDSV/issues/14

The problem is that importing const enum from a .d.ts file doesn't really work properly.

Consider the following fix to  https://github.com/leeoniya/uDSV/issues/14:
```ts
  csvSchema.cols.forEach((c) => {
    c.type = 's';
  });
```
This results in a TS error:
![image](https://github.com/user-attachments/assets/fc839b95-d276-44c6-be7f-1c44f43428a1)

You can silence the error by forcing a cast to `SchemaColumnType` like this:
```ts
  csvSchema.cols.forEach((c) => {
    c.type = 's' as SchemaColumnType;
  });
```
but this is not recommended because it essentially removes the type checking, and if `SchemaColumnType` changes, or someone passes a wrong `type` value, TypeScript will not pick up the error:

![image](https://github.com/user-attachments/assets/4257ae96-be85-4e10-8e5a-4205dc7b3f6d)

I would suggest removing the const enum from the .d.ts and replacing it with a string literal union, which I think is the correct way to provide good DX here. Like this (I'll submit this exact suggestion as a PR):

```ts
export type SchemaColumnType = 
| /** String */ 's'
| /** Number */ 'n'
| /** Date */ 'd'
| /** JSON */ 'j'
| /** Boolean_1 */ 'b:1'
| /** Boolean_t */ 'b:t'
| /** Boolean_T */ 'b:T'
| /** Boolean_true */ 'b:true'
| /** Boolean_True */ 'b:True'
| /** Boolean_TRUE */ 'b:TRUE'
| /** Boolean_y */ 'b:y'
| /** Boolean_Y */ 'b:Y'
| /** Boolean_yes */ 'b:yes'
| /** Boolean_Yes */ 'b:Yes'
| /** Boolean_YES */ 'b:YES';
```

This will also give autocomplete:
![image](https://github.com/user-attachments/assets/098127f3-75cd-4efe-9fe5-1e7b7b60ecce)

Now, the only bit where this is not *perfect* is that the single-character strings are a bit less obvious than the names of the const enum elements. And currently, TypeScript sadly does not pick up the comments next to the union elements. But once it does (https://github.com/microsoft/TypeScript/issues/38106), the comments should be included in IntelliSense.
But anyway, considering that the const enum approach is either incorrect or dangerous (depending on how you look at it), I think this is still a better alternative.

**Comment by leeoniya** [comment]
hmm, this does appear to work tho?

![image](https://github.com/user-attachments/assets/3d155396-e32b-4e36-93e9-3fba85e806ce)

**Comment by mz8i** [comment]
Could you please share the `tsconfig` there, and the TS version?

**Comment by leeoniya** [comment]
i haven't checked, but it probably doesnt compile :)

i'm fine with the proposed change, since the strings are not int enum values and not completely nonsensical, and this doesnt create the mess that a regular enum would create at build time, though that may be irrelevant for a js lib where this is just a type declaration and the lib itself does not use it.

![image](https://github.com/user-attachments/assets/48b33e54-cb77-490d-80b5-5da97b709749)

**Comment by leeoniya** [comment]
(merged https://github.com/leeoniya/uDSV/pull/16)
