### ISSUE TITLE
Const enum pitfalls...

### ISSUE THREAD

**Issue by udsv-user** [leeoniya/uDSV#6]
Use of `const enum` in [uDSV.d.ts](https://github.com/leeoniya/uDSV/blob/main/dist/uDSV.d.ts#L28) is problematic as described [here](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls). Please consider replacing it.

**Comment by leeoniya** [comment]
sooo, since this is a JS codebase, changing to regular `enum` in the `.d.ts` file is inconsequential.

the question becomes if i ever want to migrate to TS if this change would prevent inlining, which i want to retain.

i guess this is the answer:

![image](https://github.com/leeoniya/uDSV/assets/43234/268e3347-c56a-4ac4-8948-93392d7f5d0c)

the build step they link to is in a Gulpfile, so will need to be different for a Rollup/TS setup, but _should_ be straightforward.

**Comment by udsv-user** [comment]
@leeoniya Thanks for your comments. I should have explained my issue in more detail and maybe you would have a suggestion to fix it. But I did not get a chance to create an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) before. I think I have something now that should be pretty easy to reproduce. 

Let's say I create a [simple React app that uses Typescript](https://create-react-app.dev/docs/adding-typescript/) using:

```sh
npx create-react-app my-app --template typescript
```

Now I want to use your excellent `udsv` library with it so I add it:

```sh
npm i udsv
```

Then I add the following two simple lines near the top of `App.tsx`:

```tsx
import { SchemaColumnType } from 'udsv';
const foo = SchemaColumnType.Number;
```

This produces the following error on the second line above:

```txt
TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

[So, `const enum`s cannot be used with `isolatedModules`](https://www.typescriptlang.org/tsconfig#references-to-const-enum-members). Fine, so I will disable `isolatedModules` in `tsconfig.json` which eliminates this warning but does not solve the problem.

```json
    ...
    isolatedModules": false
    ...
```

Now I get the following error message(s):

```txt
udsv__WEBPACK_IMPORTED_MODULE_3__.SchemaColumnType is undefined
...
export 'SchemaColumnType' (imported as 'SchemaColumnType') was not found in 'udsv' (possible exports: inferSchema, initParser)
```

Any thoughts?

**Comment by udsv-user** [comment]
Well [phooey](https://github.com/microsoft/TypeScript/issues/40962). Enums inside `.d.ts` files are of no use in such cases.

**Comment by leeoniya** [comment]
can you check if the latest commit fixes it?

update your dependency in `package.json` with the github commit link:

```
"udsv": "leeoniya/uDSV#https://github.com/leeoniya/uDSV#0c191e8a80e7b0d78bfd0bf6ec37dc576deefbde
```

**Comment by udsv-user** [comment]
Thanks for the update, @leeoniya. However, unfortunately, I am getting the same error message (I tried the same update in my own local copy earlier and it did not work). 

I am fairly convinced after reading [this](https://github.com/microsoft/TypeScript/issues/40962) that having the `enum` just in the `.d.ts` file will not work. So, please don't waste any more of your (valuable) time on this issue. Someday, if you decide to switch to Typescript, I will drop by and help out.

**Comment by udsv-user** [comment]
A few other discussions that you might find useful in this context:

- [Exporting enum in `.d.ts` leads to „Can't resolve” error](https://stackoverflow.com/questions/63701326/exporting-enum-in-d-ts-leads-to-cant-resolve-error)
- [Enums in typescript d.ts file](https://stackoverflow.com/questions/62109542/enums-in-typescript-d-ts-file)
- [Enum from .d.ts works for value comparison but not name comparison](https://github.com/Microsoft/TypeScript/issues/432#issuecomment-51855590)
